### ISSUE TITLE
please, have script files?

### ISSUE THREAD

**Issue by FranzLiszt-1847** [Water2sea/TPGN#1]
May I ask if there is a script file available, so that, convenient to adjust params when recurrent your code.

**Comment by Water2sea** [comment]
Thank you for your interest in our work. However, we did not use a script file. Please refer to our paper for details on the parameter search space, which will facilitate experimentation on your platform. Later on, we will also share the specific parameters of our model for various tasks across all datasets to assist in reproducing the experiments. For more information about our experimental platform, please refer to our paper.
