### ISSUE TITLE
Add a requirements.txt file for dependency management

### ISSUE THREAD

**Issue by Haoxi2002** [Water2sea/TPGN#2]
Hi,
Thank you for the amazing project! It would be helpful if a requirements.txt file could be added to the repository. This file would make it easier for users to install all necessary dependencies with a single command, ensuring compatibility and simplifying setup.
For example, a basic requirements.txt could include:
```
dependency1==version  
dependency2==version  
```  
This addition could benefit new users and those looking for a quick way to get started.

**Comment by Water2sea** [comment]
Thank you for your attention to our work, the *requirements.txt* file has been updated.

**Comment by Haoxi2002** [comment]
Thanks for your work!
